app.bootstrap-servers=localhost:9092
app.topic.input=input-event
app.topic.processed=processed-event
app.topic.partitions=6
app.streams.application-id=tx-cache-streams
app.streams.state-dir=/tmp/kafka-streams
app.streams.num-threads=1
